### ISSUE TITLE
No more crawling at Instagram?

### ISSUE THREAD

**Issue by DavidKabelitz** [spicywebau/craft-embedded-assets#137]
#### Description
Hi,
using the plugin to crawl a IG post does not work anymore. The json file is more or less empty. Just embeddedAsset.html will return the embedded post. URL and other informations are not crawled.

Json File looks like thise:

`"title": "Login • Instagram",
    "description": "Welcome back to Instagram. Sign in to check out what your friends, family & interests have been capturing & sharing around the world.",
    "url": "https://www.instagram.com/accounts/login/",
    "type": "link",
    "tags": [],
    "feeds": [],
    "images": [],
    "image": null,
    "imageWidth": null,
    "imageHeight": null,
    "code": null,`

**Comment by ttempleton** [comment]
Which version of Embedded Assets are you using?  This should be working for 2.2.6, see #134 for details.

**Comment by DavidKabelitz** [comment]
The latest 2.2.6 and nope it's not working for all.

**Comment by DavidKabelitz** [comment]
Hi, this is a crawl...everything there just the url is still missing.
`{
    "title": "Office Improvements Teil2: Wir haben dazu gelernt und nicht wieder das Logo an die Wand geklebt;) Auf Beton geschraubt ist es eh viel cooler 🤘🏻💪🏻🤛🏻🤜🏻 #wearehoods #triotopkoeln",
    "description": "Welcome back to Instagram. Sign in to check out what your friends, family & interests have been capturing & sharing around the world.",
    "url": "https://www.instagram.com/accounts/login/",
    "type": "rich",
    "tags": [],
    "feeds": [],
    "images": [
        {
            "url": "https://scontent-frt3-1.cdninstagram.com/v/t51.2885-15/e35/s480x480/101009363_275863066924676_8138315198785507101_n.jpg?_nc_ht=scontent-frt3-1.cdninstagram.com&_nc_cat=108&_nc_ohc=FrcEq-UxOQgAX_QgOro&oh=95af04c51cda80b18f65ab0205c7b529&oe=5F1F95F9",
            "width": 480,
            "height": 480,
            "size": 230400,
            "mime": "image/jpeg"
        }
    ],
    "image": "https://scontent-frt3-1.cdninstagram.com/v/t51.2885-15/e35/s480x480/101009363_275863066924676_8138315198785507101_n.jpg?_nc_ht=scontent-frt3-1.cdninstagram.com&_nc_cat=108&_nc_ohc=FrcEq-UxOQgAX_QgOro&oh=95af04c51cda80b18f65ab0205c7b529&oe=5F1F95F9",
    "imageWidth": 480,
    "imageHeight": 480,`

**Comment by DavidKabelitz** [comment]
Also strange is, that everything works fine on a local dev machine. At our stage or live server it is also not working.

**Comment by ttempleton** [comment]
I also ran a test on the [demo site for the `embed/embed` library, version 3](https://oscarotero.com/embed3/demo/) (which Embedded Assets depends on for this functionality) and that seemed to be working fine.  I still wonder if viewing limits for non-members discussed in #134 might still be at play, even if it ended up not being the cause of #134.  I'll do some more testing, but if it is actually related to viewing limits, we unfortunately can't do much about it.

**Comment by DavidKabelitz** [comment]
If i do the test on the demo site i will get the same result. Everything looks good just url show the login url. Please try this post https://www.instagram.com/p/CBn2Ka8Cfmw/ i also tested on another https://www.instagram.com/p/CB3wpvYBQWM/ and the result is the same.
<img width="1247" alt="Bildschirmfoto 2020-06-26 um 15 51 08" src="https://user-images.githubusercontent.com/28010175/85864478-e021b580-b7c4-11ea-919d-15ab3d8d55f7.png">

**Comment by ttempleton** [comment]
@DavidKabelitz, I've tested both of those (and re-tested the post from #134) on the Embed 3 demo site and can confirm that I now see the URL for the login screen.  Interestingly, the [demo site for Embed 4](http://oscarotero.com/embed/demo) is showing me the correct URL, so there might be a bug in version 3.  Unfortunately we can't upgrade to Embed 4 yet because it requires PHP version 7.4+, while Craft currently requires PHP 7.0+.

We should be able to work around it, though; we do get the correct URL from the user in order to make the request to Instagram, so we could replace the login URL with that.  I will aim to have the workaround in place for the next Embedded Assets release.

**Comment by ttempleton** [comment]
This should now be fixed after updating to Embedded Assets 2.3.0 and clearing Craft's data caches.

**Comment by DavidKabelitz** [comment]
Hi, sorry it's not fixed. All instagram assets of an existing project have no more links (just links to login) after the update function below. So a week ago everything was fine, now everything is broken again.

`
if (($decodedJson['providerName'] === 'Instagram') && $this->_hasBeenWeekSince($asset->dateModified)) {
                if ($this->_hasInstagramImageExpired($decodedJson['image'])) {
                    $decodedJson = $this->_updateInstagramFile($asset, $decodedJson['url']);
                } else {
                    // if not expire yet update the date modified so it checks the file in another 7 days
                    $asset->dateModified = new \DateTime();
                    Craft::$app->getElements()->saveElement($asset);
                }
            }
`

**Comment by ttempleton** [comment]
Turns out the workaround that was applied for the initial embed was not being applied for that file update process.  Should now be fixed in Embedded Assets 2.3.2!

**Comment by DavidKabelitz** [comment]
Ok just to double check because it feels like that. All json files that are "broken" now and just include the login links won't work. We need to crawl all those files manually again? Tons of work for us.

**Comment by ttempleton** [comment]
Sorry, yes, any Instagram embeds that reverted to the login URL would need to be replaced.  There should be no need to update any asset fields where the embeds are being used, though, if you replace the files using the Replace button that appears on the asset index page when you select an embedded asset.
