### ISSUE TITLE
Embed not saving

### ISSUE THREAD

**Issue by johnwbaxter** [spicywebau/craft-embedded-assets#70]
Hi,

This was working fine until today which is odd, but we cannot embed anything now.

So, go to assets, click "Embed", paste in youtube or vimeo url and hit save. The modal goes away but nothing is saved in the asset location.

There are no errors logged so i have no idea what is the issue here!

Thanks

John

**Comment by johnwbaxter** [comment]
So the issue seems to be that It can't cope with sub folders. I removed the sub folder i was using for video and it all worked again.

**Comment by jamiewade** [comment]
@benjamminf +1. Was also experiencing exactly the same issue, came here to post an issue but can see John beat me to it!

I'm uploading my embedded media into a `media` folder (which is restricted in the field settings) and as you can see it doesn't work:

![bug](https://user-images.githubusercontent.com/6672331/41149165-c869f404-6b02-11e8-879b-a8f7971ef34a.gif)

What's actually happening here is the assets are being saved, but *not* in the folder in the field settings. If I go to the root of my asset source, all the media objects are there instead.

**Comment by mark-chief** [comment]
@benjamminf +1 I am also running in to this issue with Sub Folders anything, is there a fix?

**Comment by Ho0m3s** [comment]
@benjamminf @mark-chief  Also running into this issue, did you people figure out a fix? The plugin seem to only be able to save either at the root or the first sub folder under that root. All attempts to save an embed file end up in that first sub folder when trying to create the asset in any other subfolder.  But it works fine if at the root and trying to create asset there.

**Comment by marksimons** [comment]
@Ho0m3s Nope - still happening and no fix.

**Comment by goinnovative** [comment]
I fixed this by allowing file type **JSON** instead or additional to video for the file-field.

**Comment by monachilada** [comment]
@benjamminf Are you monitoring this? I think a lot of us would appreciate a shout out that you're aware of the problem.

If it helps, it seems like in these cases that line 30 in `client/src/main.js`:

`const getFolderId = () => this.getDefaultSourceKey().split(':')[1]|0`

... is defaulting to `0` for whatever reason. I can't figure out exactly why, but I have a feeling it might have something to do with dynamic variables in the asset folder path, as when I set it to something static it seems to work closer to what is expected.

**Comment by khamer** [comment]
+1.

@goinnovative - I'm not sure what file-field you mean - this issue seems to happen even trying to upload directly via /admin/assets without any associated fields.

**Comment by kyle51north** [comment]
I've create a pull request that should fix this issue. #84 

Hopefully @benjamminf can take a look at this in the near future.

**Comment by kylerits** [comment]
This is still happening for me. I have tried saving several different videos only for the asset not to be added to the list. This is a fairly new problem that I have noticed after updating to Craft 3.1.6.1
